### ISSUE TITLE
Status for 1st milestone

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/monitoring-integration#27]
Dashboards
==========

Here is my feedback of Grafana dashboards of [1st
milestone](https://github.com/Tendrl/specifications/milestone/2).

This feedback is based on Sankarshan's description of what to fosus on
in this milestone:

-   Installation
-   Are we able to get this stack up against Gluster
-   Are able to automatically detect a Gluster cluster
-   Are the metrics available and displayed

Based on my work with the 1st milestone builds, there are few details to
be checked and addressed, but the overall goals were reached. The
testing was not exhaustive, rather a minimal setup and testing approach
to check the whole stack was used (even though I used stress tool to
check the values few times).

For the record, here is a list of tendrl packages installed on Tendrl
Server:

    # rpm -qa tendrl*
    tendrl-monitoring-integration-1.0.0-1.el7.centos.noarch
    tendrl-commons-1.5.0-1.el7.centos.noarch
    tendrl-api-1.5.0-1.el7.centos.noarch
    tendrl-node-agent-1.5.0-1.el7.centos.noarch
    tendrl-ui-1.5.0-1.el7.centos.noarch
    tendrl-api-httpd-1.5.0-1.el7.centos.noarc
    # rpm -qa | egrep '(grafana|graphite)'
    graphite-web-0.9.16-1.el7.noarch
    grafana-4.4.3-1.x86_64

I create GlusterFS cluster via gdeploy (`gdeploy-2.0.2-7.noarch`):

    [hosts]
    mbukatov-usm1-gl1.example.com
    mbukatov-usm1-gl2.example.com
    mbukatov-usm1-gl3.example.com
    mbukatov-usm1-gl4.example.com

    [peer]
    action=probe
    ignore_peer_errors=no

    [backend-setup]
    devices=vdb,vdc
    vgs=vg_gluster_1,vg_gluster_2
    pools=pool_gluster_1,pool_gluster_2
    lvs=lv_gluster_1,lv_gluster_2
    mountpoints=/mnt/glusterbrick_1,/mnt/glusterbrick_2
    brick_dirs=/mnt/glusterbrick_1/1,/mnt/glusterbrick_2/2

    [volume]
    action=create
    volname=volume_theodosianus_magnus
    replica=yes
    replica_count=2
    force=yes

As you can see, I have 4 [KVM](https://www.linux-kvm.org/page/Main_Page)
virtual machines in the trusted storage pool, all with block devices vdb
and vdc of size 1TB backed by a thin provisioned qcow2 image.

Then I installed Tendrl using my *work in progress* branch for
tendrl-ansible:

<https://github.com/Tendrl/tendrl-ansible/pull/22>

```
---

- include: workaround.disable-selinux.yml
- include: workaround.disable-firewall.yml

- hosts: all
  user: root
  tasks:
    - name: Update all installed packages
      yum:
        name: '*'
        state: latest

- hosts: tendrl-server
  user: root
  vars:
    etcd_ip_address: "{{ ansible_default_ipv4.address }}"
    graphite_ip_address: "{{ ansible_default_ipv4.address }}"
  roles:
    - grafana-repo
    - tendrl-copr
    - tendrl-server

- hosts: gluster-servers
  user: root
  vars:
    etcd_ip_address: "{{ hostvars[groups['tendrl-server'][0]].ansible_default_ipv4.address }}"
    graphite_ip_address: "{{ hostvars[groups['tendrl-server'][0]].ansible_default_ipv4.address }}"
    tendrl_gluster_provisioning_support: True
  roles:
    - tendrl-copr
    - gluster-gdeploy-copr
    - tendrl-storage-node
```

and imported the cluster into Tendrl via API (import via UI is not part
of 1st milestone).

If you are interested, see my temporary ad-hoc script here:

<https://gist.github.com/mbukatov/f09b8ee509d16d8f8e0a4a4035c36c2c>

I also described how import API currently works here:

<https://github.com/Tendrl/api/issues/234#issuecomment-322261105>

I let the cluster to run idle for few days, to accumulate historical
data and while doing that, I noticed that issue with missing task data
is aplicable to the import feature after rescope as well, for more
details see: <https://github.com/Tendrl/api/issues/219>

I also noticed the same problem with gluster locking, which Lubos
noticed and investigated here:
<https://github.com/Tendrl/gluster-integration/issues/358>

    # gluster volume status                                          
    Another transaction is in progress for volume_theodosianus_magnus. Please try again after sometime.

At A Glance Dashboard
---------------------

![screenshot_20170818_102750](https://user-images.githubusercontent.com/4759819/29458180-1ed23f58-841e-11e7-917a-58f19e99ff26.png)

On this dashboard, there are counters for:

-   Status - **value not present**, shows N/A
-   Quorum status - **value not present**, shows N/A
-   Hosts: value is correct
-   Volumes: value is correct
-   Bricks: value is correct
-   Hosts Up: value is correct
-   Hosts Down: value is correct
-   Volumes Up: value is correct
-   Volumes Down: value is correct
-   Bricks Up: **value not present**, shows N/A
-   Bricks Down: **value not present**, shows N/A

**Cluster Unitization chart** is shown, but the value seems to be
unreasonably high (note that my volume has few TB), which suggests to the
problem of units of measure in this case (the volume is empty).

**IOPS Reads** and **IPS Writes** charts show no data points, which is
likely because I didn't enable required debugging translator in gluster.

**Inode Utilization** chart looks ok.

Bricks Dashboard
----------------

![screenshot_20170818_104929](https://user-images.githubusercontent.com/4759819/29458229-572f0354-841e-11e7-81f8-b4e98e41625f.png)

**Bricks Utilization** chart has similar problem: the units are missing,
and suggest far larger utilization then there actually is.

**Inode Utilization** chart looks ok.

Moreover, the labels in charts are all the same (eg. see label
`|mnt|glusterbrick_1|1` repeated four times, each time with a different
color). In my case, it would make more sense to name the labels by
hostname of the machine which hosts the brick, but I'm not sure if that
was the general intention here.

Hosts Dashboard
---------------

![screenshot_20170818_105624](https://user-images.githubusercontent.com/4759819/29458241-6117d936-841e-11e7-9a43-ad96b6d0ad93.png)
![screenshot_20170818_105740](https://user-images.githubusercontent.com/4759819/29458247-67a716ae-841e-11e7-96da-041e4827e6fb.png)
![screenshot_20170818_105756](https://user-images.githubusercontent.com/4759819/29458251-6d0db95e-841e-11e7-8ca0-bcaaf0860c91.png)
![screenshot_20170818_105813](https://user-images.githubusercontent.com/4759819/29458255-72e1c96a-841e-11e7-9bec-586a24bc121b.png)

There are values reported for:

-   Memory Free: works
-   Memory Used: works
-   Storage Free: works, but the problem is that "storage" here means
    all devices of the machine, including both system disk and brick
    devices, which may not be expected
-   Storage Used: works (but with the same problem as above)

Then there are charts for:

-   Memory: works
-   Storage: works (but with clarification what storage means as stated
    above)
-   Swap: OK, reports no data points because swap is disabled on storage
    machines. When I added and activated a swap device, datapoints were
    shown.
-   CPU: Seems kind of ok (the problem described in BZ 1358461 is not
    there: value here combines both system and user cpu load), but it
    would be much better to report at least system and user cpu load
    separately ...
-   Throughput - Cluster Network: looks ok, units of measure could be
    more precise (it reads just K, but it would be better to include
    full unit of measure)

Volumes Dashboard
-----------------

![screenshot_20170818_133623](https://user-images.githubusercontent.com/4759819/29458262-7d033262-841e-11e7-9c82-5fb863cb2202.png)

Values reported:

-   Volume status: seems to work
-   Brick Count: seems working
-   Connection Count: reports N/A (**should this work already?**)

Chart for **Volume Utilization** have again problem with **units of
measure**.

Resource Consumption
--------------------

While the cluster did basically nothing during the few days I let it
collect the data, I have noticed that:

-   Memory consumption is growing, with a different rate on each
    machine, reaching about 20% memory utilization. On all machines most
    memory is taken by `glusterd` process.
-   Cpu load is about 20% on 3 machines, while almost 0% on one machine.
    On those 3 machines, most cpu were used by `tendrl-node-agent`
    process.
